// GESTION DES CONTACTS "Ajout, Suppression, Modification"
export const ADD_CONTACT = 'ADD_CONTACT';
export const DEL_CONTACT = 'DEL_CONTACT';
export const UP_CONTACT = 'UP_CONTACT';

export const ADD_CONTACT_SUCCESS = 'ADD_CONTACT_SUCCESS';
export const DEL_CONTACT_SUCCESS = 'DEL_CONTACT_SUCCESS';
export const UP_CONTACT_SUCCESS = 'UP_CONTACT_SUCCESS';

export const ADD_CONTACT_FAILED = 'ADD_CONTACT_FAILED';
export const DEL_CONTACT_FAILED = 'DEL_CONTACT_FAILED';
export const UP_CONTACT_FAILED = 'UP_CONTACT_FAILED';


export const SEARCH_MAP = 'SEARCH_MAP';
export const SEARCH_MAP_SUCCESS = 'SEARCH_MAP_SUCCESS';
export const SEARCH_MAP_FAILED = 'SEARCH_MAP_FAILED';